(in-package #:crypto-kit/test)

(defun %json-whitespace-p (character)
  (member character '(#\Space #\Tab #\Return #\Newline)))

(defun %json-space (stream)
  (loop for character = (peek-char nil stream nil nil)
        while (and character (%json-whitespace-p character))
        do (read-char stream)))

(defun %json-string (stream)
  (unless (char= (read-char stream) #\") (error "JSON string expected"))
  (with-output-to-string (out)
    (loop for character = (read-char stream)
          until (char= character #\")
          do (if (char= character #\\)
                 (let ((escaped (read-char stream)))
                   (write-char (case escaped
                                 (#\" #\") (#\\ #\\) (#\/ #\/)
                                 (#\b #\Backspace) (#\f #\Page)
                                 (#\n #\Newline) (#\r #\Return) (#\t #\Tab)
                                 (otherwise (error "Unsupported JSON escape"))) out))
                 (write-char character out)))))

(defun %json-value (stream)
  (%json-space stream)
  (case (peek-char nil stream)
    (#\" (%json-string stream))
    (#\[ (read-char stream)
          (let (values)
            (%json-space stream)
            (unless (char= (peek-char nil stream) #\])
              (loop
                (push (%json-value stream) values)
                (%json-space stream)
                (if (char= (peek-char nil stream) #\,)
                    (read-char stream)
                    (return))))
            (read-char stream)
            (nreverse values)))
    (#\{ (read-char stream)
          (let (values)
            (%json-space stream)
            (unless (char= (peek-char nil stream) #\})
              (loop
                (%json-space stream)
                (let ((key (%json-string stream)))
                  (%json-space stream)
                  (unless (char= (read-char stream) #\:) (error "JSON colon expected"))
                  (push (cons key (%json-value stream)) values))
                (%json-space stream)
                (if (char= (peek-char nil stream) #\,)
                    (read-char stream)
                    (return))))
            (read-char stream)
            (nreverse values)))
    (otherwise
     (let ((token (with-output-to-string (out)
                    (loop for character = (peek-char nil stream)
                          while (and character
                                      (not (or (%json-whitespace-p character)
                                               (find character " ,]}"))))
                          do (write-char (read-char stream) out)))))
       (cond ((string= token "true") t) ((string= token "false") nil)
             ((string= token "null") nil) (t (parse-integer token)))))))

(defun %json-get (object key)
  (cdr (assoc key object :test #'string=)))

(defun %rsa-hex (string)
  (let ((result (make-array (/ (length string) 2) :element-type '(unsigned-byte 8))))
    (dotimes (index (length result) result)
      (setf (aref result index)
            (parse-integer string :start (* index 2) :end (+ (* index 2) 2) :radix 16)))))

(defparameter +rsa-wycheproof-files+
  '(("rsa_signature_2048_sha256_test.json" :pkcs1 :sha256)
    ("rsa_signature_3072_sha256_test.json" :pkcs1 :sha256)
    ("rsa_pss_2048_sha256_mgf1_0_test.json" :pss :sha256)
    ("rsa_pss_2048_sha256_mgf1_32_test.json" :pss :sha256)
    ("rsa_pss_3072_sha256_mgf1_32_test.json" :pss :sha256)
    ("rsa_pss_4096_sha256_mgf1_32_test.json" :pss :sha256)))

(defun %rsa-run-wycheproof-file (file kind algorithm)
  (let* ((path (merge-pathnames (format nil "t/fixtures/wycheproof-rsa/~A" file)
                                (asdf:system-source-directory "cl-crypto-kit")))
         (document (with-open-file (stream path) (%json-value stream)))
         (passed 0) (total 0))
    (dolist (group (%json-get document "testGroups"))
      (let* ((key (%json-get group "publicKey"))
             (modulus (parse-integer (%json-get key "modulus") :radix 16))
             (exponent (parse-integer (%json-get key "publicExponent") :radix 16))
             (salt-length (%json-get group "sLen")))
        (dolist (test (%json-get group "tests"))
          (incf total)
          (let* ((message (%rsa-hex (%json-get test "msg")))
                 (signature (%rsa-hex (%json-get test "sig")))
                 (actual (ecase kind
                           (:pkcs1 (rsa-verify-pkcs1-v1_5 algorithm modulus exponent message signature))
                           (:pss (rsa-verify-pss algorithm modulus exponent message signature
                                                 :salt-length salt-length))))
                 (result (%json-get test "result")))
            (if (or (string= result "acceptable")
                    (eq actual (string= result "valid")))
                (incf passed)
                (error "RSA Wycheproof mismatch ~A tcId ~D" file (%json-get test "tcId")))))))
    (format t "RSA Wycheproof ~A: ~D/~D passed~%" file passed total)
    (values passed total)))

(defun run-rsa-tests ()
  (let ((total 0) (passed 0))
    (dolist (spec +rsa-wycheproof-files+)
      (multiple-value-bind (file-passed file-total)
          (apply #'%rsa-run-wycheproof-file spec)
        (incf passed file-passed) (incf total file-total)))
    (format t "RSA verification: ~D/~D Wycheproof vectors passed~%" passed total)
    t))
