(in-package #:crypto-kit/test)

(defun run-ec-tests ()
  (let* ((c crypto-kit::+p256+)
         (g (crypto-kit::ec-point (crypto-kit::ec-curve-gx c)
                                  (crypto-kit::ec-curve-gy c)))
         (encoded (crypto-kit::ec-encode-point g c)))
    (unless (crypto-kit::ec-on-curve-p g c) (error "P-256 generator is off curve"))
    (unless (= (crypto-kit::ec-octets-int (p256-ecdh 1 encoded))
               (crypto-kit::ec-curve-gx c)) (error "P-256 ECDH scalar one"))
    (let ((bad (copy-seq encoded)))
      (setf (aref bad (1- (length bad))) (logxor (aref bad (1- (length bad))) 1))
      (handler-case (progn (p256-ecdh 1 bad) (error "off-curve point accepted"))
        (crypto-error () t)))
    (unless (not (p384-point-on-curve-p (make-array 97 :element-type '(unsigned-byte 8)
                                                     :initial-element 0)))
      (error "invalid P-384 point accepted")))
  (format t "cl-crypto-kit: EC boundary tests passed~%") t)
