(in-package #:crypto-kit/test)

(defun %ec-json-space-p (c) (member c '(#\Space #\Tab #\Return #\Newline)))
(defun %ec-json-string (s)
  (unless (char= (read-char s) #\") (error "JSON string expected"))
  (with-output-to-string (out)
    (loop for c = (read-char s) until (char= c #\") do
      (if (char= c #\\) (write-char (read-char s) out) (write-char c out)))))
(defun %ec-json-value (s)
  (loop while (%ec-json-space-p (peek-char nil s nil nil)) do (read-char s))
  (case (peek-char nil s)
    (#\" (%ec-json-string s))
    (#\[ (read-char s)
          (let (values)
            (loop while (%ec-json-space-p (peek-char nil s nil nil)) do (read-char s))
            (unless (char= (peek-char nil s) #\])
              (loop
                (loop while (%ec-json-space-p (peek-char nil s nil nil)) do (read-char s))
                (push (%ec-json-value s) values)
                (loop while (%ec-json-space-p (peek-char nil s nil nil)) do (read-char s))
                (if (char= (peek-char nil s) #\,) (read-char s) (return))))
            (read-char s) (nreverse values)))
    (#\{ (read-char s)
          (let (values)
            (loop while (%ec-json-space-p (peek-char nil s nil nil)) do (read-char s))
            (unless (char= (peek-char nil s) #\})
              (loop
                (loop while (%ec-json-space-p (peek-char nil s nil nil)) do (read-char s))
                (let ((key (%ec-json-string s)))
                  (loop while (%ec-json-space-p (peek-char nil s nil nil)) do (read-char s))
                  (read-char s) (push (cons key (%ec-json-value s)) values))
                (loop while (%ec-json-space-p (peek-char nil s nil nil)) do (read-char s))
                (if (char= (peek-char nil s) #\,) (read-char s) (return))))
            (read-char s) (nreverse values)))
    (otherwise
     (let ((token (with-output-to-string (out)
                    (loop for c = (peek-char nil s nil nil)
                          while (and c (not (find c " ,]}")))
                          do (write-char (read-char s) out)))))
       (cond ((string= token "true") t) ((string= token "false") nil)
             ((string= token "null") nil) (t (parse-integer token)))))))
(defun %ec-json-get (o k) (cdr (assoc k o :test #'string=)))
(defun %ec-hex (s)
  (let ((v (make-array (/ (length s) 2) :element-type '(unsigned-byte 8))))
    (dotimes (i (length v) v) (setf (aref v i) (parse-integer s :start (* i 2) :end (+ 2 (* i 2)) :radix 16)))))
(defun %ec-public-tail (s size)
  (let ((v (%ec-hex s)))
    (let ((start (- (length v) (+ (* 2 size) 1))))
      (when (and (= size 32) (>= start 26)
                 (equalp (subseq v 0 26)
                         (%ec-hex "3059301306072a8648ce3d020106082a8648ce3d030107034200"))
                 (= (aref v start) 4))
        (subseq v start)))))

(defun %ec-public-point (s)
  (let ((v (%ec-hex s)) (der (%ec-public-tail s 32)))
    (cond ((and (= (length v) 65) (= (aref v 0) 4))
           (values v :raw-uncompressed))
          (der (values der :der-wrapped))
          (t (values nil :unsupported)))))

(defun %run-ec-wycheproof-ecdsa (file curve hash size)
  (declare (ignore size))
  (let ((path (merge-pathnames (format nil "t/fixtures/wycheproof-ec/~A" file)
                               (asdf:system-source-directory "cl-crypto-kit")))
        (total 0) (passed 0))
    (with-open-file (s path)
      (let ((doc (%ec-json-value s)))
        (dolist (group (%ec-json-get doc "testGroups"))
          (let ((public (%ec-hex (%ec-json-get (%ec-json-get group "publicKey") "uncompressed"))))
            (dolist (test (%ec-json-get group "tests"))
              (incf total)
              (let ((actual (ecdsa-verify curve hash (%ec-hex (%ec-json-get test "msg")) public
                                           (%ec-hex (%ec-json-get test "sig")))))
                (if (or (and (string= (%ec-json-get test "result") "valid") actual)
                        (and (not (string= (%ec-json-get test "result") "valid")) (not actual)))
                    (incf passed)
                    (error "ECDSA Wycheproof mismatch ~A tcId ~D" file (%ec-json-get test "tcId")))))))))
    (format t "ECDSA Wycheproof ~A: ~D/~D passed~%" file passed total)
    (values passed total)))

(defun %run-ec-wycheproof-ecdh (file)
  (let ((path (merge-pathnames (format nil "t/fixtures/wycheproof-ec/~A" file)
                               (asdf:system-source-directory "cl-crypto-kit")))
        (total 0) (passed 0))
    (with-open-file (s path)
      (let ((doc (%ec-json-value s)))
        (let ((declared (%ec-json-get doc "numberOfTests")))
        (dolist (group (%ec-json-get doc "testGroups"))
          (dolist (test (%ec-json-get group "tests"))
            (incf total)
            (multiple-value-bind (pub encoding)
                (%ec-public-point (%ec-json-get test "public"))
              (let* ((valid (and pub (handler-case
                                         (equalp (p256-ecdh (%ec-hex (%ec-json-get test "private")) pub)
                                                 (%ec-hex (%ec-json-get test "shared")))
                                       (crypto-error () nil))))
                     (result (%ec-json-get test "result"))
                     (expected (string= result "valid"))
                     (acceptable (string= result "acceptable"))
                     (matches (or (and expected valid)
                                  (and (not expected) (not acceptable) (not valid))
                                  (and acceptable (or (not valid)
                                                      (and (eq encoding :raw-uncompressed)
                                                           valid))))))
                (if matches
                  (incf passed)
                  (error "ECDH Wycheproof mismatch tcId ~D (~A)"
                         (%ec-json-get test "tcId") encoding))))))
        (unless (= declared total)
          (error "ECDH Wycheproof count mismatch: declared ~D, read ~D" declared total)))))
    (format t "ECDH Wycheproof ~A: ~D/~D passed~%" file passed total)
    (values passed total)))

(defun %nist-der-int (hex)
  (let ((v (%ec-hex hex)))
    (if (>= (aref v 0) 128) (concatenate '(vector (unsigned-byte 8)) #(0) v) v)))
(defun %nist-value (line start)
  (string-trim '(#\Space #\Tab #\Return #\Newline) (subseq line start)))
(defun %nist-der-signature (r s)
  (let* ((rv (%nist-der-int r)) (sv (%nist-der-int s))
         (body (concatenate '(vector (unsigned-byte 8)) (vector 2 (length rv)) rv
                            (vector 2 (length sv)) sv)))
    (concatenate '(vector (unsigned-byte 8)) (vector 48 (length body)) body)))
(defun %run-nist-ecdsa ()
  (let ((path (merge-pathnames "t/fixtures/nist-ecdsa/SigVer.rsp" (asdf:system-source-directory "cl-crypto-kit")))
        (curve nil) (hash nil) (msg nil) (qx nil) (qy nil) (r nil) (ss nil) (result nil) (total 0) (passed 0))
    (labels ((flush ()
              (when (and curve msg qx qy r ss result
                         (member curve '(:p256 :p384)) (member hash '(:sha256 :sha384)))
                (incf total)
                (let* ((pub (crypto-kit::concat-octets #(4) (%ec-hex qx) (%ec-hex qy)))
                       (actual (ecdsa-verify curve hash (%ec-hex msg) pub (%nist-der-signature r ss)))
                       (expected (char= result #\P)))
                  (if (eq actual expected) (incf passed)
                      (error "NIST ECDSA mismatch ~A" total))))))
      (with-open-file (s path)
        (loop for line = (read-line s nil nil) while line do
          (cond
            ((and (> (length line) 2) (char= (char line 0) #\[))
             (flush) (setf curve (cond ((search "P-256" line) :p256) ((search "P-384" line) :p384))
                           hash (cond ((search "SHA-256" line) :sha256) ((search "SHA-384" line) :sha384))
                           msg nil qx nil qy nil r nil ss nil result nil))
            ((search "Msg = " line) (flush) (setf msg (%nist-value line 6) qx nil qy nil r nil ss nil result nil))
            ((search "Qx = " line) (setf qx (%nist-value line 5)))
            ((search "Qy = " line) (setf qy (%nist-value line 5)))
            ((search "R = " line) (setf r (%nist-value line 4)))
            ((search "S = " line) (setf ss (%nist-value line 4)))
            ((search "Result = " line) (setf result (char (%nist-value line 9) 0)))))
        (flush)))
    (format t "NIST ECDSA P-256/P-384 SigVer: ~D/~D passed~%" passed total)
    (values passed total)))

(defun run-ec-tests ()
  (dotimes (attempt 8)
    (multiple-value-bind (private public) (p256-generate-keypair)
      (declare (ignore public))
      (let ((scalar (crypto-kit::ec-octets-int private)))
        (unless (and (> scalar 0)
                     (< scalar (crypto-kit::ec-curve-n crypto-kit::+p256+)))
          (error "Generated P-256 private scalar is outside [1,n-1]")))))
  (let* ((c crypto-kit::+p256+)
         (g (crypto-kit::ec-point (crypto-kit::ec-curve-gx c)
                                  (crypto-kit::ec-curve-gy c)))
         (encoded (crypto-kit::ec-encode-point g c)))
    (unless (crypto-kit::ec-on-curve-p g c) (error "P-256 generator is off curve"))
    (unless (= (crypto-kit::ec-octets-int (p256-ecdh 1 encoded))
               (crypto-kit::ec-curve-gx c)) (error "P-256 ECDH scalar one"))
    (dolist (private (list (make-array 31 :element-type '(unsigned-byte 8))
                           (make-array 33 :element-type '(unsigned-byte 8))))
      (handler-case
          (progn (p256-ecdh private encoded)
                 (error "P-256 private key with invalid length was accepted"))
        (crypto-error () t)))
    (let ((bad (copy-seq encoded)))
      (setf (aref bad (1- (length bad))) (logxor (aref bad (1- (length bad))) 1))
      (handler-case (progn (p256-ecdh 1 bad) (error "off-curve point accepted"))
        (crypto-error () t)))
    (unless (not (p384-point-on-curve-p (make-array 97 :element-type '(unsigned-byte 8)
                                                     :initial-element 0)))
      (error "invalid P-384 point accepted")))
  (%run-ec-wycheproof-ecdh "ecdh_secp256r1_test.json")
  (%run-ec-wycheproof-ecdh "ecdh_secp256r1_ecpoint_test.json")
  (%run-ec-wycheproof-ecdsa "ecdsa_secp256r1_sha256_test.json" :p256 :sha256 32)
  (%run-ec-wycheproof-ecdsa "ecdsa_secp384r1_sha384_test.json" :p384 :sha384 48)
  (%run-nist-ecdsa)
  (format t "cl-crypto-kit: EC boundary and vector tests passed~%") t)
