(in-package #:crypto-kit)

(declaim (inline %aes-xtime %aes-gf-mul %aes-sbox)
         (ftype (function ((unsigned-byte 8)) (unsigned-byte 8)) %aes-xtime %aes-sbox)
         (ftype (function ((unsigned-byte 8) (unsigned-byte 8)) (unsigned-byte 8)) %aes-gf-mul)
         (optimize (speed 3) (safety 0) (debug 0)))

(defstruct (aes-context (:constructor %make-aes-context (round-keys rounds)))
  round-keys rounds)

(defun %aes-xtime (x)
  (declare (type (unsigned-byte 8) x))
  (logand #xff
          (logxor (ash x 1)
                  (logand #x1b (- (ash x -7))))))

(defun %aes-gf-mul (a b)
  (declare (type (unsigned-byte 8) a b))
  (let ((r 0))
    (declare (type (unsigned-byte 8) r))
    (dotimes (i 8 r)
      (setf r (logxor r (logand a (- (logand b 1)))))
      (setf a (%aes-xtime a) b (ash b -1)))))

(defun %aes-sbox (x)
  ;; The inverse is x^254.  This fixed addition chain also maps zero to zero,
  ;; so S-box evaluation has no input-dependent branch or table lookup.
  (declare (type (unsigned-byte 8) x))
  (let* ((x (logand x #xff))
         (x2 (%aes-gf-mul x x))
         (x4 (%aes-gf-mul x2 x2))
         (x8 (%aes-gf-mul x4 x4))
         (x16 (%aes-gf-mul x8 x8))
         (x32 (%aes-gf-mul x16 x16))
         (x64 (%aes-gf-mul x32 x32))
         (x128 (%aes-gf-mul x64 x64))
         (y (%aes-gf-mul
             (%aes-gf-mul (%aes-gf-mul x2 x4) x8)
             (%aes-gf-mul (%aes-gf-mul x16 x32)
                          (%aes-gf-mul x64 x128)))))
    (flet ((rot (n) (logand #xff (logior (ash y n) (ash y (- n 8))))))
      (logand #xff (logxor y (rot 1) (rot 2) (rot 3) (rot 4) #x63)))))

(defun %aes-sub-word (word)
  (logior (ash (%aes-sbox (ldb (byte 8 24) word)) 24)
          (ash (%aes-sbox (ldb (byte 8 16) word)) 16)
          (ash (%aes-sbox (ldb (byte 8 8) word)) 8)
          (%aes-sbox (ldb (byte 8 0) word))))

(defun %aes-key-expansion (key)
  (let* ((nk (/ (length key) 4)) (nr (+ nk 6))
         (words (make-array (* 4 (1+ nr)) :element-type '(unsigned-byte 32)))
         (rcon 1))
    (dotimes (i nk) (setf (aref words i)
                          (logior (ash (aref key (* i 4)) 24)
                                  (ash (aref key (+ (* i 4) 1)) 16)
                                  (ash (aref key (+ (* i 4) 2)) 8)
                                  (aref key (+ (* i 4) 3)))))
    (loop for i from nk below (length words) do
      (let ((temp (aref words (1- i))))
        (when (zerop (mod i nk))
          (setf temp (logior (ash (ldb (byte 8 16) temp) 24)
                             (ash (ldb (byte 8 8) temp) 16)
                             (ash (ldb (byte 8 0) temp) 8)
                             (ldb (byte 8 24) temp)))
          (setf temp (logxor (%aes-sub-word temp) (ash rcon 24)))
          (setf rcon (%aes-xtime rcon)))
        (when (and (= nk 8) (= (mod i nk) 4))
          (setf temp (%aes-sub-word temp)))
        (setf (aref words i) (logxor (aref words (- i nk)) temp))))
    (values words nr)))

(defun %aes-make (key size)
  (unless (= (length key) size) (error "AES~D requires a ~D-byte key" (* 8 size) size))
  (multiple-value-bind (round-keys rounds) (%aes-key-expansion key)
    (%make-aes-context round-keys rounds)))

(defun aes-128 (key) (%aes-make key 16))
(defun aes-192 (key) (%aes-make key 24))
(defun aes-256 (key) (%aes-make key 32))

(defun %aes-add-round-key (state keys round)
  (dotimes (c 4)
    (let ((word (aref keys (+ (* round 4) c))))
      (dotimes (r 4)
        (setf (aref state (+ (* c 4) r))
              (logxor (aref state (+ (* c 4) r))
                      (ldb (byte 8 (* 8 (- 3 r))) word)))))))

(defun %aes-sub-bytes (state)
  (dotimes (i 16) (setf (aref state i) (%aes-sbox (aref state i)))))

(defun %aes-shift-rows (s)
  (let ((old (copy-seq s)))
    (dotimes (r 4)
      (dotimes (c 4)
        (setf (aref s (+ (* c 4) r))
              (aref old (+ (* (mod (+ c r) 4) 4) r)))))))

(defun %aes-mix-columns (s)
  (dotimes (c 4)
    (let* ((p (* c 4)) (a0 (aref s p)) (a1 (aref s (+ p 1)))
           (a2 (aref s (+ p 2))) (a3 (aref s (+ p 3))))
      (setf (aref s p) (logxor (%aes-gf-mul a0 2) (%aes-gf-mul a1 3) a2 a3)
            (aref s (+ p 1)) (logxor a0 (%aes-gf-mul a1 2) (%aes-gf-mul a2 3) a3)
            (aref s (+ p 2)) (logxor a0 a1 (%aes-gf-mul a2 2) (%aes-gf-mul a3 3))
            (aref s (+ p 3)) (logxor (%aes-gf-mul a0 3) a1 a2 (%aes-gf-mul a3 2))))))

(defun aes-encrypt-block (cipher block)
  (let* ((ctx (if (typep cipher 'aes-context) cipher
                  (ecase (length cipher)
                    (16 (aes-128 cipher))
                    (24 (aes-192 cipher))
                    (32 (aes-256 cipher)))))
         (state (copy-seq block)) (keys (aes-context-round-keys ctx))
         (rounds (aes-context-rounds ctx)))
    (unless (= (length block) 16) (error "AES blocks are 16 bytes"))
    (%aes-add-round-key state keys 0)
    (loop for round from 1 below rounds do
      (%aes-sub-bytes state) (%aes-shift-rows state) (%aes-mix-columns state)
      (%aes-add-round-key state keys round))
    (%aes-sub-bytes state) (%aes-shift-rows state) (%aes-add-round-key state keys rounds)
    state))
