(in-package #:crypto-kit)
(declaim (inline %c32 %cr %le32 %put-le32 %quarter))
(defun %c32 (x) (declare (type integer x)) (logand #xffffffff x))
(defun %cr (x n)
  (declare (type (unsigned-byte 32) x) (type fixnum n))
  (%c32 (logior (ash x n) (ldb (byte n (- 32 n)) x))))
(defun %le32 (a p)
  (declare (type (simple-array (unsigned-byte 8) (*)) a) (type fixnum p))
  (logior (aref a p) (ash (aref a (+ p 1)) 8)
          (ash (aref a (+ p 2)) 16) (ash (aref a (+ p 3)) 24)))
(defun %put-le32 (n a p)
  (declare (type (unsigned-byte 32) n)
           (type (simple-array (unsigned-byte 8) (*)) a)
           (type fixnum p))
  (dotimes (i 4)
    (setf (aref a (+ p i)) (logand #xff (ash n (* -8 i))))))
(defun %quarter (v a b c d)
  (setf (aref v a) (%c32 (+ (aref v a) (aref v b))) (aref v d) (%cr (logxor (aref v d) (aref v a)) 16)
        (aref v c) (%c32 (+ (aref v c) (aref v d))) (aref v b) (%cr (logxor (aref v b) (aref v c)) 12)
        (aref v a) (%c32 (+ (aref v a) (aref v b))) (aref v d) (%cr (logxor (aref v d) (aref v a)) 8)
        (aref v c) (%c32 (+ (aref v c) (aref v d))) (aref v b) (%cr (logxor (aref v b) (aref v c)) 7)))
(defun %chacha-block-into (key counter nonce out v x)
  (declare (type (simple-array (unsigned-byte 8) (*)) key nonce out)
           (type (simple-array (unsigned-byte 32) (16)) v x)
           (type integer counter))
    (setf (aref v 0) #x61707865 (aref v 1) #x3320646e (aref v 2) #x79622d32 (aref v 3) #x6b206574)
    (dotimes (i 8) (setf (aref v (+ 4 i)) (%le32 key (* i 4))))
    (setf (aref v 12) (%c32 counter)
          (aref v 13) (%le32 nonce 0) (aref v 14) (%le32 nonce 4) (aref v 15) (%le32 nonce 8))
    (replace x v)
    (dotimes (i 10) (%quarter x 0 4 8 12) (%quarter x 1 5 9 13) (%quarter x 2 6 10 14) (%quarter x 3 7 11 15) (%quarter x 0 5 10 15) (%quarter x 1 6 11 12) (%quarter x 2 7 8 13) (%quarter x 3 4 9 14))
    (dotimes (i 16) (setf (aref x i) (%c32 (+ (aref x i) (aref v i)))))
    (dotimes (i 16 out) (%put-le32 (aref x i) out (* i 4))))
(defun %chacha-block (key counter nonce)
  (let ((v (make-array 16 :element-type '(unsigned-byte 32)))
        (x (make-array 16 :element-type '(unsigned-byte 32)))
        (out (make-array 64 :element-type '(unsigned-byte 8))))
    (%chacha-block-into key counter nonce out v x)))
(defun chacha20-block (key counter nonce)
  (unless (and (= (length key) 32) (= (length nonce) 12))
    (crypto-error "ChaCha20 requires a 32-octet key and 12-octet nonce"))
  (%chacha-block key counter nonce))
(defun chacha20-keystream (key counter nonce length)
  (unless (and (= (length key) 32) (= (length nonce) 12))
    (crypto-error "ChaCha20 requires a 32-octet key and 12-octet nonce"))
  (when (minusp length)
    (crypto-error "ChaCha20 output length must not be negative"))
  (let ((out (make-array length :element-type '(unsigned-byte 8)))
        (counter (%c32 counter))
        (block (make-array 64 :element-type '(unsigned-byte 8)))
        (v (make-array 16 :element-type '(unsigned-byte 32)))
        (x (make-array 16 :element-type '(unsigned-byte 32))))
    (loop for position from 0 below length by 64
          for block-counter from 0
          do (%chacha-block-into key (%c32 (+ counter block-counter)) nonce block v x)
             (replace out block
                      :start1 position :end1 (min length (+ position 64))))
    out))
