(in-package #:crypto-kit)
(defun %c32 (x) (logand #xffffffff x))
(defun %cr (x n) (logior (ldb (byte (- 32 n) n) x) (ash x (- n))))
(defun %le32 (a p) (logior (aref a p) (ash (aref a (+ p 1)) 8) (ash (aref a (+ p 2)) 16) (ash (aref a (+ p 3)) 24)))
(defun %put-le32 (n a p) (dotimes (i 4) (setf (aref a (+ p i)) (logand #xff (ash n (* -8 i))))))
(defun %quarter (v a b c d)
  (setf (aref v a) (%c32 (+ (aref v a) (aref v b))) (aref v d) (%cr (logxor (aref v d) (aref v a)) 16)
        (aref v c) (%c32 (+ (aref v c) (aref v d))) (aref v b) (%cr (logxor (aref v b) (aref v c)) 12)
        (aref v a) (%c32 (+ (aref v a) (aref v b))) (aref v d) (%cr (logxor (aref v d) (aref v a)) 8)
        (aref v c) (%c32 (+ (aref v c) (aref v d))) (aref v b) (%cr (logxor (aref v b) (aref v c)) 7)))
(defun %chacha-block (key counter nonce)
  (let ((v (make-array 16)) (x (make-array 16)))
    (setf (aref v 0) #x61707865 (aref v 1) #x3320646e (aref v 2) #x79622d32 (aref v 3) #x6b206574)
    (dotimes (i 8) (setf (aref v (+ 4 i)) (%le32 key (* i 4))))
    (setf (aref v 12) counter (aref v 13) (%le32 nonce 0) (aref v 14) (%le32 nonce 4) (aref v 15) (%le32 nonce 8))
    (replace x v)
    (dotimes (i 10) (declare (ignore i)) (%quarter x 0 4 8 12) (%quarter x 1 5 9 13) (%quarter x 2 6 10 14) (%quarter x 3 7 11 15) (%quarter x 0 5 10 15) (%quarter x 1 6 11 12) (%quarter x 2 7 8 13) (%quarter x 3 4 9 14))
    (dotimes (i 16) (setf (aref x i) (%c32 (+ (aref x i) (aref v i)))))
    (let ((out (make-array 64 :element-type '(unsigned-byte 8)))) (dotimes (i 16 out) (%put-le32 (aref x i) out (* i 4))))))
(defun chacha20-keystream (key counter nonce length)
  (let ((out (make-array length :element-type '(unsigned-byte 8))))
    (loop for p from 0 below length by 64 for block from counter do (replace out (%chacha-block key block nonce) :start1 p :end1 (min length (+ p 64)))) out))
