(in-package #:crypto-kit)

(defun der-length (v pos)
  (when (>= pos (length v)) (return-from der-length (values nil nil)))
  (let ((b (aref v pos)))
    (if (< b 128) (values b (1+ pos))
        (let ((n (logand b 127)))
          (when (or (zerop n) (> n 2) (> (+ pos 1 n) (length v))
                    (and (> n 1) (zerop (aref v (1+ pos)))))
            (return-from der-length (values nil nil)))
          (let ((length (read-be v (1+ pos) n)))
            (when (and (= n 1) (< length 128))
              (return-from der-length (values nil nil)))
            (values length (+ pos 1 n)))))))
(defun der-integer (v pos end)
  (unless (and (< pos end) (= (aref v pos) 2)) (return-from der-integer (values nil nil)))
  (multiple-value-bind (len start) (der-length v (1+ pos))
    (unless (and len start (> len 0) (<= (+ start len) end)
                 (or (and (< (aref v start) 128)
                          (or (not (zerop (aref v start)))
                              (and (> len 1) (>= (aref v (1+ start)) 128))))
                     (and (= (aref v start) 0) (> len 1)
                          (>= (aref v (1+ start)) 128))))
      (return-from der-integer (values nil nil)))
    (if (and (= (aref v start) 0) (> len 1))
        (values (read-be v (1+ start) (1- len)) (+ start len))
        (values (read-be v start len) (+ start len)))))
(defun parse-ecdsa-signature (signature)
  (unless (and (> (length signature) 6) (= (aref signature 0) 48)) (return-from parse-ecdsa-signature nil))
  (multiple-value-bind (len pos) (der-length signature 1)
    (unless (and len pos (= (+ pos len) (length signature))) (return-from parse-ecdsa-signature nil))
    (multiple-value-bind (r next) (der-integer signature pos (+ pos len))
      (when r
        (multiple-value-bind (s end) (der-integer signature next (+ pos len))
          (and s (= end (+ pos len)) (values r s)))))))

(defun ecdsa-verify (curve hash-algorithm message public-key signature)
  (let* ((c (ec-curve-for curve))
         (q (handler-case (ec-decode-point public-key c) (crypto-error () nil)))
         (parsed (and q (multiple-value-list (parse-ecdsa-signature signature)))))
    (when (and q parsed (= (length parsed) 2))
      (let ((r (first parsed)) (s (second parsed)) (n (ec-curve-n c)))
        (when (and (> r 0) (< r n) (> s 0) (< s n))
          (let* ((e (read-be (digest hash-algorithm message) 0 (digest-length hash-algorithm)))
                 (shift (- (* 8 (digest-length hash-algorithm)) (integer-length n)))
                 (z (if (> shift 0) (ash e (- shift)) e))
                 (w (ec-pow-mod s (- n 2) n))
                 (u1 (mod (* z w) n)) (u2 (mod (* r w) n))
                 (p (ec-add (ec-mul u1 (ec-point (ec-curve-gx c) (ec-curve-gy c)) c)
                            (ec-mul u2 q c) c)))
            (and p (= (mod (car p) n) r))))))))
(defun ec-curve-for (curve) (case curve ((:p256 p256) +p256+) ((:p384 p384) +p384+) (otherwise (crypto-error "Unknown EC curve ~S" curve))))
(defun ecdsa-verify-p256 (message public-key signature) (ecdsa-verify :p256 :sha256 message public-key signature))
(defun ecdsa-verify-p384 (message public-key signature) (ecdsa-verify :p384 :sha384 message public-key signature))
