(in-package #:crypto-kit)

(deftype octets () '(simple-array (unsigned-byte 8) (*)))
(defconstant +u32+ #xffffffff)
(defconstant +u64+ #xffffffffffffffff)

(defun prime-p (n)
  (and (> n 1) (loop for d from 2 to (isqrt n) never (zerop (mod n d)))))
(defun primes (n)
  (loop with p = 2 repeat n collect p do (setf p (loop for q from (1+ p)
                                                        when (prime-p q) return q))))
(defun floor-root (n scale power)
  (let ((lo 0) (hi 1))
    (loop while (<= (expt hi power) n) do (setf hi (* hi 2)))
    (loop while (< (1+ lo) hi) do
      (let ((mid (ash (+ lo hi) -1)))
        (if (<= (expt mid power) n) (setf lo mid) (setf hi mid)))) lo))
(defun generated-constants (count bits power)
  (let ((scale (ash 1 bits)) (modulus (ash 1 bits)))
    (mapcar (lambda (p) (mod (floor-root (* p (expt scale power)) scale power)
                              modulus))
            (primes count))))
(defun rotr (x n bits)
  (logior (ash x (- n)) (ash (ldb (byte n 0) x) (- bits n))))
(defun addmod (bits &rest xs) (mod (reduce #'+ xs) (ash 1 bits)))
(defun read-be (octets start size)
  (loop for i below size for v = 0 then (logior (ash v 8) (aref octets (+ start i)))
        finally (return v)))
(defun put-be (value size)
  (let ((out (make-array size :element-type '(unsigned-byte 8))))
    (loop for i below size do (setf (aref out i) (ldb (byte 8 (* 8 (- size i 1))) value))) out))
(defun concat-octets (&rest vectors)
  (let ((out (make-array (reduce #'+ vectors :key #'length) :element-type '(unsigned-byte 8)))
        (pos 0))
    (dolist (v vectors out) (replace out v :start1 pos) (incf pos (length v)))))

(defstruct (digest-state (:constructor %make-state)) algorithm h buffer length)
(defun digest-params (algorithm)
  (case algorithm
    (:sha1 (values 32 20 64)) (:sha256 (values 32 32 64))
    (:sha384 (values 64 48 128)) (:sha512 (values 64 64 128))
    (otherwise (crypto-error "Unknown digest algorithm ~S" algorithm))))
(defun digest-length (algorithm) (nth-value 1 (digest-params algorithm)))
(defun initial-state (algorithm)
  (case algorithm
    (:sha1 (vector #x67452301 #xefcdab89 #x98badcfe #x10325476 #xc3d2e1f0))
    (:sha256 #( #x6a09e667 #xbb67ae85 #x3c6ef372 #xa54ff53a #x510e527f #x9b05688c #x1f83d9ab #x5be0cd19))
    (:sha384 #( #xcbbb9d5dc1059ed8 #x629a292a367cd507 #x9159015a3070dd17 #x152fecd8f70e5939 #x67332667ffc00b31 #x8eb44a8768581511 #xdb0c2e0d64f98fa7 #x47b5481dbefa4fa4))
    (:sha512 #( #x6a09e667f3bcc908 #xbb67ae8584caa73b #x3c6ef372fe94f82b #xa54ff53a5f1d36f1 #x510e527fade682d1 #x9b05688c2b3e6c1f #x1f83d9abfb41bd6b #x5be0cd19137e2179))))
(defun make-digest (algorithm)
  (multiple-value-bind (word output block) (digest-params algorithm)
    (declare (ignore word output block))
    (%make-state :algorithm algorithm :h (initial-state algorithm)
                 :buffer (make-array 0 :element-type '(unsigned-byte 8)) :length 0)))

(defun sha1-compress (h block)
  (let ((w (make-array 80 :initial-element 0)) (a (aref h 0)) (b (aref h 1))
        (c (aref h 2)) (d (aref h 3)) (e (aref h 4)))
    (loop for i below 16 do (setf (aref w i) (read-be block (* i 4) 4)))
    (loop for i from 16 below 80 do (setf (aref w i) (rol32 (logxor (aref w (- i 3))
                                                                      (aref w (- i 8))
                                                                      (aref w (- i 14))
                                                                      (aref w (- i 16))) 1)))
    (loop for i below 80 for f = (cond ((< i 20) (logior (logand b c) (logand (lognot b) d)))
                                       ((< i 40) (logxor b c d)) ((< i 60) (logior (logand b c)
                                       (logand b d) (logand c d))) (t (logxor b c d)))
          for k = (aref #(1518500249 1859775393 2400959708 3395469782) (floor i 20))
          for total = (addmod 32 (rol32 a 5) f e k (aref w i))
          do (psetf e d d c c (rol32 b 30) b a a total))
    (loop for i below 5 do (setf (aref h i) (addmod 32 (aref h i) (nth i (list a b c d e))))) h))
(defun rol32 (x n) (ldb (byte 32 0) (logior (ash x n) (ash (ldb (byte n 0) x) (- 32 n)))))
(defun sha256-compress (h block)
  (let ((w (make-array 64 :initial-element 0)) (a (aref h 0)) (b (aref h 1))
        (c (aref h 2)) (d (aref h 3)) (e (aref h 4)) (f (aref h 5))
        (g (aref h 6)) (hh (aref h 7)) (k (coerce (generated-constants 64 32 3) 'vector)))
    (loop for i below 16 do (setf (aref w i) (read-be block (* i 4) 4)))
    (loop for i from 16 below 64 for x = (aref w (- i 15)) for y = (aref w (- i 2))
          do (setf (aref w i) (addmod 32 (rotr x 7 32) (rotr x 18 32) (ash x -3)
                                      (aref w (- i 16)) (rotr y 17 32) (rotr y 19 32) (ash y -10))))
    (loop for i below 64 for s1 = (logxor (rotr e 6 32) (rotr e 11 32) (rotr e 25 32))
          for ch = (logxor (logand e f) (logand (lognot e) g))
          for t1 = (addmod 32 hh s1 ch (aref k i) (aref w i))
          for s0 = (logxor (rotr a 2 32) (rotr a 13 32) (rotr a 22 32))
          for maj = (logxor (logand a b) (logand a c) (logand b c))
          for t2 = (addmod 32 s0 maj)
          do (setf hh g g f f e e (addmod 32 d t1) d c c b b a a
                   (addmod 32 t1 t2)))
    (loop for i below 8 for x in (list a b c d e f g hh)
          do (setf (aref h i) (addmod 32 (aref h i) x))) h))
(defun sha512-compress (h block)
  ;; SHA-512 uses the same schedule with 64-bit words; constants are generated from cube roots.
  (let ((w (make-array 80 :initial-element 0)) (v (coerce h 'list))
        (k (coerce (generated-constants 80 64 3) 'vector)))
    (loop for i below 16 do (setf (aref w i) (read-be block (* i 8) 8)))
    (loop for i from 16 below 80 for x = (aref w (- i 15)) for y = (aref w (- i 2))
          do (setf (aref w i) (addmod 64 (rotr x 1 64) (rotr x 8 64) (ash x -7)
                                      (aref w (- i 16)) (rotr y 19 64) (rotr y 61 64) (ash y -6))))
    (loop for i below 80 for a = (nth 0 v) for b = (nth 1 v) for c = (nth 2 v)
          for d = (nth 3 v) for e = (nth 4 v) for f = (nth 5 v) for g = (nth 6 v)
          for hh = (nth 7 v) for s1 = (logxor (rotr e 14 64) (rotr e 18 64) (rotr e 41 64))
          for ch = (logxor (logand e f) (logand (lognot e) g))
          for t1 = (addmod 64 hh s1 ch (aref k i) (aref w i))
          for s0 = (logxor (rotr a 28 64) (rotr a 34 64) (rotr a 39 64))
          for maj = (logxor (logand a b) (logand a c) (logand b c))
          for t2 = (addmod 64 s0 maj)
          do (setf v (list (addmod 64 t1 t2) a b c (addmod 64 d t1) e f g)))
    (loop for i below 8 for x in v
          do (setf (aref h i) (addmod 64 (aref h i) x))) h))

(defun compress (state block)
  (case (digest-state-algorithm state) (:sha1 (sha1-compress (digest-state-h state) block))
    (:sha256 (sha256-compress (digest-state-h state) block))
    ((:sha384 :sha512) (sha512-compress (digest-state-h state) block))))
(defun digest-update (state input &key (start 0) end)
  (let* ((end (or end (length input))) (old (digest-state-buffer state))
         (all (make-array (+ (length old) (- end start)) :element-type '(unsigned-byte 8))))
    (replace all old) (replace all input :start1 (length old) :start2 start :end2 end)
    (loop with block = (nth-value 2 (digest-params (digest-state-algorithm state)))
          for pos from 0 by block while (<= (+ pos block) (length all))
          do (compress state (subseq all pos (+ pos block))) finally
             (setf (digest-state-buffer state) (subseq all pos)))
    (incf (digest-state-length state) (- end start)) state))
(defun digest-copy (state)
  (let ((copy (copy-digest-state state)))
    (setf (digest-state-h copy) (copy-seq (digest-state-h state))
          (digest-state-buffer copy) (copy-seq (digest-state-buffer state))) copy))
(defun digest-final (state)
  (let* ((copy (digest-copy state)) (word (nth-value 0 (digest-params (digest-state-algorithm copy))))
         (block (nth-value 2 (digest-params (digest-state-algorithm copy))))
         (len (digest-state-length copy)) (pad (make-array (+ 1 (mod (- block 1 (length (digest-state-buffer copy))
                                                                    (if (= word 64) 16 8)) block)
                                                (if (= word 64) 16 8))
                              :element-type '(unsigned-byte 8) :initial-element 0)))
    (setf (aref pad 0) #x80)
    (let ((bits (* len 8)) (n (length pad)))
      (loop for i below (if (= word 64) 16 8) do
        (setf (aref pad (+ (- n (if (= word 64) 16 8)) i))
              (ldb (byte 8 (* 8 (- (if (= word 64) 16 8) i 1))) bits))))
    (digest-update copy pad)
    (apply #'concat-octets (loop for x across (digest-state-h copy) collect (put-be x (/ word 8))))))
(defun digest (algorithm octets) (digest-final (digest-update (make-digest algorithm) octets)))
