(in-package #:crypto-kit)

(defstruct (ec-curve (:constructor make-ec-curve (prime a b gx gy n size))) prime a b gx gy n size)
(defparameter +p256+
  (make-ec-curve #xffffffff00000001000000000000000000000000ffffffffffffffffffffffff
                 #xffffffff00000001000000000000000000000000fffffffffffffffffffffffc
                 #x5ac635d8aa3a93e7b3ebbd55769886bc651d06b0cc53b0f63bce3c3e27d2604b
                 #x6b17d1f2e12c4247f8bce6e563a440f277037d812deb33a0f4a13945d898c296
                 #x4fe342e2fe1a7f9b8ee7eb4a7c0f9e162bce33576b315ececbb6406837bf51f5
                 #xffffffff00000000ffffffffffffffffbce6faada7179e84f3b9cac2fc632551 32))

(defun ec-mod (x c) (mod x (ec-curve-prime c)))
(defun ec-pow (x e c) (let ((r 1) (b (ec-mod x c))) (loop while (> e 0) do (when (oddp e) (setf r (ec-mod (* r b) c))) (setf b (ec-mod (* b b) c) e (ash e -1))) r))
(defun ec-pow-mod (x e modulus)
  (let ((r 1) (b (mod x modulus)))
    (loop while (> e 0) do
      (when (oddp e) (setf r (mod (* r b) modulus)))
      (setf b (mod (* b b) modulus) e (ash e -1)))
    r))
(defun ec-inv (x c) (if (zerop x) 0 (ec-pow x (- (ec-curve-prime c) 2) c)))
(defun ec-point (x y) (cons x y))
(defun ec-infinity-p (q) (null q))

(defstruct (ec-jacobian (:constructor ec-jacobian (x y z))) x y z)
(defstruct (ec-rcb-point (:constructor ec-rcb-point (x y z))) x y z)
(defun ec-rcb-affine (q c)
  (let* ((z (ec-rcb-point-z q))
         (zi (ec-pow z (- (ec-curve-prime c) 2) c)))
    (ec-point (ec-mod (* (ec-rcb-point-x q) zi) c)
              (ec-mod (* (ec-rcb-point-y q) zi) c))))
(defun ec-rcb-add (p q c)
  (let* ((x1 (ec-rcb-point-x p)) (y1 (ec-rcb-point-y p)) (z1 (ec-rcb-point-z p))
         (x2 (ec-rcb-point-x q)) (y2 (ec-rcb-point-y q)) (z2 (ec-rcb-point-z q))
         (a (ec-curve-a c))
         (b3 (ec-mod (* 3 (ec-curve-b c)) c))
         (t0 (ec-mod (* x1 x2) c))
         (t1 (ec-mod (* y1 y2) c))
         (t2 (ec-mod (* z1 z2) c))
         (t3 (ec-mod (- (* (+ x1 y1) (+ x2 y2)) t0 t1) c))
         (t4 (ec-mod (- (* (+ x1 z1) (+ x2 z2)) t0 t2) c))
         (t5 (ec-mod (- (* (+ y1 z1) (+ y2 z2)) t1 t2) c)))
    (setf z1 (ec-mod (* a t4) c)
          x1 (ec-mod (* b3 t2) c)
          z1 (ec-mod (+ x1 z1) c)
          x1 (ec-mod (- t1 z1) c)
          z1 (ec-mod (+ t1 z1) c)
          y1 (ec-mod (* x1 z1) c)
          t1 (ec-mod (+ t0 t0 t0) c)
          t2 (ec-mod (* a t2) c)
          t4 (ec-mod (* b3 t4) c)
          t1 (ec-mod (+ t1 t2) c)
          t2 (ec-mod (* a (- t0 t2)) c)
          t4 (ec-mod (+ t4 t2) c)
          t0 (ec-mod (* t1 t4) c)
          y1 (ec-mod (+ y1 t0) c)
          t0 (ec-mod (* t5 t4) c)
          x1 (ec-mod (- (* t3 x1) t0) c)
          t0 (ec-mod (* t3 t1) c)
          z1 (ec-mod (+ (* t5 z1) t0) c))
    (ec-rcb-point x1 y1 z1)))
(defun ec-rcb-cswap (left right bit)
  (let* ((mask (- bit))
         (dx (logand mask (logxor (ec-rcb-point-x left) (ec-rcb-point-x right))))
         (dy (logand mask (logxor (ec-rcb-point-y left) (ec-rcb-point-y right))))
         (dz (logand mask (logxor (ec-rcb-point-z left) (ec-rcb-point-z right)))))
    (values (ec-rcb-point (logxor (ec-rcb-point-x left) dx)
                          (logxor (ec-rcb-point-y left) dy)
                          (logxor (ec-rcb-point-z left) dz))
            (ec-rcb-point (logxor (ec-rcb-point-x right) dx)
                          (logxor (ec-rcb-point-y right) dy)
                          (logxor (ec-rcb-point-z right) dz)))))
(defun ec-rcb-ladder (k q c bits)
  (let ((r0 (ec-rcb-point 0 1 0))
        (r1 (ec-rcb-point (car q) (cdr q) 1)))
    (loop for i downfrom (1- bits) to 0 do
      (let ((bit (ldb (byte 1 i) k)))
        (multiple-value-setq (r0 r1) (ec-rcb-cswap r0 r1 bit))
        (let ((sum (ec-rcb-add r0 r1 c))
              (double (ec-rcb-add r0 r0 c)))
          (setf r1 sum r0 double))
        (multiple-value-setq (r0 r1) (ec-rcb-cswap r0 r1 bit))))
    r0))
(defun ec-jacobian-point (q)
  (and q (ec-jacobian (car q) (cdr q) 1)))
(defun ec-jacobian-double (q c)
  (if (or (null q) (zerop (ec-jacobian-y q)))
      nil
      (let* ((x (ec-jacobian-x q)) (y (ec-jacobian-y q)) (z (ec-jacobian-z q))
             (yy (ec-mod (* y y) c))
             (s (ec-mod (* 4 x yy) c))
             (m (ec-mod (+ (* 3 x x)
                           (* (ec-curve-a c) (expt z 4))) c))
             (nx (ec-mod (- (* m m) (* 2 s)) c))
             (ny (ec-mod (- (* m (- s nx)) (* 8 yy yy)) c))
             (nz (ec-mod (* 2 y z) c)))
        (ec-jacobian nx ny nz))))
(defun ec-jacobian-add (left right c)
  (cond ((null left) right) ((null right) left)
        (t (let* ((z1 (ec-jacobian-z left)) (z2 (ec-jacobian-z right))
                  (z1sq (ec-mod (* z1 z1) c)) (z2sq (ec-mod (* z2 z2) c))
                  (u1 (ec-mod (* (ec-jacobian-x left) z2sq) c))
                  (u2 (ec-mod (* (ec-jacobian-x right) z1sq) c))
                  (s1 (ec-mod (* (ec-jacobian-y left) z2 z2sq) c))
                  (s2 (ec-mod (* (ec-jacobian-y right) z1 z1sq) c)))
             (if (= u1 u2)
                 (if (= s1 s2) (ec-jacobian-double left c) nil)
                 (let* ((h (ec-mod (- u2 u1) c))
                        (r (ec-mod (- s2 s1) c))
                        (h2 (ec-mod (* h h) c))
                        (h3 (ec-mod (* h h2) c))
                        (nx (ec-mod (- (* r r) h3 (* 2 u1 h2)) c))
                        (ny (ec-mod (- (* r (- (* u1 h2) nx)) (* s1 h3)) c))
                        (nz (ec-mod (* h z1 z2) c)))
                   (ec-jacobian nx ny nz)))))))
(defun ec-jacobian-shamir (u1 u2 g q c)
  (let* ((gp (ec-jacobian-point g))
         (qp (ec-jacobian-point q))
         (gq (ec-jacobian-add gp qp c))
         (r nil)
         (bits (max (integer-length u1) (integer-length u2))))
    (loop for i downfrom (1- bits) to 0 do
      (setf r (ec-jacobian-double r c))
      (case (+ (if (logbitp i u1) 2 0) (if (logbitp i u2) 1 0))
        (1 (setf r (ec-jacobian-add r qp c)))
        (2 (setf r (ec-jacobian-add r gp c)))
        (3 (setf r (ec-jacobian-add r gq c)))))
    r))
(defun ec-jacobian-cswap (left right bit)
  (let* ((mask (- bit))
         (lx (if left (ec-jacobian-x left) 0))
         (ly (if left (ec-jacobian-y left) 0))
         (lz (if left (ec-jacobian-z left) 0))
         (rx (if right (ec-jacobian-x right) 0))
         (ry (if right (ec-jacobian-y right) 0))
         (rz (if right (ec-jacobian-z right) 0))
         (lf (if left 1 0)) (rf (if right 1 0))
         (dx (logand mask (logxor lx rx)))
         (dy (logand mask (logxor ly ry)))
         (dz (logand mask (logxor lz rz)))
         (df (logand mask (logxor lf rf))))
    (values
     (if (zerop (logxor lf df)) nil
         (ec-jacobian (logxor lx dx) (logxor ly dy) (logxor lz dz)))
     (if (zerop (logxor rf df)) nil
         (ec-jacobian (logxor rx dx) (logxor ry dy) (logxor rz dz))))))
(defun ec-jacobian-ladder (k q c bits)
  ;; Scalar bits select only the arithmetic-mask swap; the loop width is fixed.
  (let* ((r0 (ec-jacobian-point q))
         (r1 (ec-jacobian-double r0 c)))
    (loop for i downfrom (- bits 2) to 0 do
      (let ((bit (ldb (byte 1 i) k)))
        (multiple-value-setq (r0 r1) (ec-jacobian-cswap r0 r1 bit))
        (let ((sum (ec-jacobian-add r0 r1 c))
              (double (ec-jacobian-double r0 c)))
          (setf r1 sum r0 double))
        (multiple-value-setq (r0 r1) (ec-jacobian-cswap r0 r1 bit))))
    r0))
(defun ec-jacobian-affine (q c)
  (when q
    (let* ((z (ec-jacobian-z q))
           (zi (ec-inv z c))
           (zi2 (ec-mod (* zi zi) c)))
      (ec-point (ec-mod (* (ec-jacobian-x q) zi2) c)
                (ec-mod (* (ec-jacobian-y q) zi2 zi) c)))))
(defun ec-add (p q c)
  (cond ((null p) q) ((null q) p)
        ((= (car p) (car q))
         (if (= (mod (+ (cdr p) (cdr q)) (ec-curve-prime c)) 0) nil
             (let* ((m (ec-mod (* (+ (* 3 (expt (car p) 2)) (ec-curve-a c))
                                   (ec-inv (* 2 (cdr p)) c)) c))
                    (x (ec-mod (- (expt m 2) (* 2 (car p))) c)))
               (ec-point x (ec-mod (- (* m (- (car p) x)) (cdr p)) c)))))
        (t (let* ((m (ec-mod (* (- (cdr q) (cdr p))
                                (ec-inv (- (car q) (car p)) c)) c))
                   (x (ec-mod (- (expt m 2) (car p) (car q)) c)))
             (ec-point x (ec-mod (- (* m (- (car p) x)) (cdr p)) c))))))

(defun ec-on-curve-p (q c)
  (and q (integerp (car q)) (integerp (cdr q))
       (< (car q) (ec-curve-prime c)) (< (cdr q) (ec-curve-prime c))
       (= (mod (ec-pow (cdr q) 2 c) (ec-curve-prime c))
          (mod (+ (ec-pow (car q) 3 c)
                  (* (ec-curve-a c) (car q)) (ec-curve-b c)) (ec-curve-prime c)))))

(defun ec-cswap (left right bit)
  ;; The scalar bit selects with a mask. Bignum arithmetic remains
  ;; implementation-dependent in timing; the ladder removes explicit
  ;; secret-dependent control flow and table lookups from this operation.
  (let* ((mask (- bit))
         (lx (if left (car left) 0)) (ly (if left (cdr left) 0))
         (rx (if right (car right) 0)) (ry (if right (cdr right) 0))
         (lf (if left 1 0)) (rf (if right 1 0))
         (dx (logand mask (logxor lx rx))) (dy (logand mask (logxor ly ry)))
         (df (logand mask (logxor lf rf))))
    (values (if (zerop (logxor lf df)) nil (cons (logxor lx dx) (logxor ly dy)))
            (if (zerop (logxor rf df)) nil (cons (logxor rx dx) (logxor ry dy))))))

(defun ec-mul (k q c &key fixed)
  (let ((r0 nil) (r1 q) (bits (or fixed (integer-length k))))
    (loop for i downfrom (1- bits) to 0 do
      (let ((bit (ldb (byte 1 i) k)))
        (multiple-value-setq (r0 r1) (ec-cswap r0 r1 bit))
        (let ((sum (ec-add r0 r1 c)) (double (ec-add r0 r0 c)))
          (setf r1 sum r0 double))
        (multiple-value-setq (r0 r1) (ec-cswap r0 r1 bit)))) r0))

(defun ec-octets-int (v) (read-be v 0 (length v)))
(defun ec-int-octets (x n) (put-be x n))
(defun ec-decode-point (octets c)
  (let ((n (ec-curve-size c)))
    (unless (and (= (length octets) (1+ (* 2 n))) (= (aref octets 0) 4))
      (crypto-error "Invalid uncompressed EC point encoding"))
    (let ((q (ec-point (read-be octets 1 n) (read-be octets (1+ n) n))))
      (unless (ec-on-curve-p q c) (crypto-error "EC point is not on curve")) q)))
(defun ec-encode-point (q c)
  (unless (ec-on-curve-p q c) (crypto-error "Cannot encode invalid EC point"))
  (concat-octets #(4) (ec-int-octets (car q) (ec-curve-size c))
                 (ec-int-octets (cdr q) (ec-curve-size c))))

(defun p256-ecdh (private-key public-key)
  (let* ((q (ec-decode-point public-key +p256+))
         (k (if (arrayp private-key) (ec-octets-int private-key) private-key)))
    (unless (and (integerp k) (> k 0) (< k (ec-curve-n +p256+)))
      (crypto-error "Invalid P-256 private scalar"))
    ;; Adding 3n preserves kP and keeps the 258-bit ladder width fixed.
    (let ((shared (ec-rcb-affine
                   (ec-rcb-ladder (+ (* 3 (ec-curve-n +p256+)) k)
                                  q +p256+ 258)
                   +p256+)))
      (unless shared (crypto-error "Invalid EC shared point"))
      (ec-int-octets (car shared) 32))))
