(in-package #:crypto-kit)

(declaim (inline %poly1305-le32 %poly1305-store32))

(defun %poly1305-le32 (octets position)
  (logior (aref octets position)
          (ash (aref octets (+ position 1)) 8)
          (ash (aref octets (+ position 2)) 16)
          (ash (aref octets (+ position 3)) 24)))

(defun %poly1305-store32 (value octets position)
  (dotimes (i 4)
    (setf (aref octets (+ position i))
          (logand #xff (ash value (* -8 i))))))

(defun poly1305 (key message)
  "Return the RFC 8439 Poly1305 tag for MESSAGE under the 32-byte KEY."
  (unless (= (length key) 32)
    (error "Poly1305 key must contain 32 octets."))
  (let* ((mask26 #x3ffffff)
         (r0 (logand (%poly1305-le32 key 0) mask26))
         (r1 (logand (ash (%poly1305-le32 key 3) -2) #x3ffff03))
         (r2 (logand (ash (%poly1305-le32 key 6) -4) #x3ffc0ff))
         (r3 (logand (ash (%poly1305-le32 key 9) -6) #x3f03fff))
         (r4 (logand (ash (%poly1305-le32 key 12) -8) #xfffff))
         (s1 (* r1 5))
         (s2 (* r2 5))
         (s3 (* r3 5))
         (s4 (* r4 5))
         (h0 0) (h1 0) (h2 0) (h3 0) (h4 0)
         (block (make-array 16 :element-type '(unsigned-byte 8))))
    (loop with position = 0
          while (< position (length message)) do
            (let* ((remaining (- (length message) position))
                   (count (min remaining 16))
                   (full (= count 16)))
              (fill block 0)
              (replace block message :start1 0 :start2 position :end2 (+ position count))
              (unless full (setf (aref block count) 1))
              (let* ((m0 (logand (%poly1305-le32 block 0) mask26))
                     (m1 (logand (ash (%poly1305-le32 block 3) -2) mask26))
                     (m2 (logand (ash (%poly1305-le32 block 6) -4) mask26))
                     (m3 (logand (ash (%poly1305-le32 block 9) -6) mask26))
                     (m4 (logand (ash (%poly1305-le32 block 12) -8) mask26))
                     (d0 (+ (* h0 r0) (* h1 s4) (* h2 s3) (* h3 s2) (* h4 s1) m0))
                     (d1 (+ (* h0 r1) (* h1 r0) (* h2 s4) (* h3 s3) (* h4 s2) m1))
                     (d2 (+ (* h0 r2) (* h1 r1) (* h2 r0) (* h3 s4) (* h4 s3) m2))
                     (d3 (+ (* h0 r3) (* h1 r2) (* h2 r1) (* h3 r0) (* h4 s4) m3))
                     (d4 (+ (* h0 r4) (* h1 r3) (* h2 r2) (* h3 r1) (* h4 r0)
                            m4 (if full (ash 1 24) 0)))
                     (c (ash d0 -26)))
                (setf h0 (logand d0 mask26)
                      d1 (+ d1 c)
                      c (ash d1 -26)
                      h1 (logand d1 mask26)
                      d2 (+ d2 c)
                      c (ash d2 -26)
                      h2 (logand d2 mask26)
                      d3 (+ d3 c)
                      c (ash d3 -26)
                      h3 (logand d3 mask26)
                      d4 (+ d4 c)
                      c (ash d4 -26)
                      h4 (logand d4 mask26)
                      h0 (+ h0 (* c 5))
                      c (ash h0 -26)
                      h0 (logand h0 mask26)
                      h1 (+ h1 c)))
              (incf position count))
          finally
             (let* ((c (ash h1 -26)))
               (setf h1 (logand h1 mask26)
                     h2 (+ h2 c)
                     c (ash h2 -26)
                     h2 (logand h2 mask26)
                     h3 (+ h3 c)
                     c (ash h3 -26)
                     h3 (logand h3 mask26)
                     h4 (+ h4 c)
                     c (ash h4 -26)
                     h4 (logand h4 mask26)
                     h0 (+ h0 (* c 5))
                     c (ash h0 -26)
                     h0 (logand h0 mask26)
                     h1 (+ h1 c))
               (let* ((g0 (+ h0 5))
                      (c (ash g0 -26))
                      (g0 (logand g0 mask26))
                      (g1 (+ h1 c))
                      (c (ash g1 -26))
                      (g1 (logand g1 mask26))
                      (g2 (+ h2 c))
                      (c (ash g2 -26))
                      (g2 (logand g2 mask26))
                      (g3 (+ h3 c))
                      (c (ash g3 -26))
                      (g3 (logand g3 mask26))
                      (g4 (+ h4 c (- #x4000000)))
                      (mask (lognot (ash g4 -63)))
                      (g4 (logand g4 mask26))
                      (not-mask (lognot mask))
                      (h0 (logior (logand h0 not-mask) (logand g0 mask)))
                      (h1 (logior (logand h1 not-mask) (logand g1 mask)))
                      (h2 (logior (logand h2 not-mask) (logand g2 mask)))
                      (h3 (logior (logand h3 not-mask) (logand g3 mask)))
                      (h4 (logior (logand h4 not-mask) (logand g4 mask)))
                      (f0 (+ (logior h0 (ash h1 26)) (%poly1305-le32 key 16)))
                      (f1 (+ (logior (ash h1 -6) (ash h2 20)) (%poly1305-le32 key 20)
                             (ash f0 -32)))
                      (f2 (+ (logior (ash h2 -12) (ash h3 14)) (%poly1305-le32 key 24)
                             (ash f1 -32)))
                      (f3 (+ (logior (ash h3 -18) (ash h4 8)) (%poly1305-le32 key 28)
                             (ash f2 -32)))
                      (tag (make-array 16 :element-type '(unsigned-byte 8))))
                 (%poly1305-store32 f0 tag 0)
                 (%poly1305-store32 f1 tag 4)
                 (%poly1305-store32 f2 tag 8)
                 (%poly1305-store32 f3 tag 12)
                 (return-from poly1305 tag))))))

(export 'poly1305)
