(in-package #:crypto-kit)

(defun %rsa-mgf1 (algorithm seed length)
  (let ((output (make-array length :element-type '(unsigned-byte 8)))
        (counter 0) (position 0))
    (loop while (< position length)
          for block = (digest algorithm
                              (concat-octets seed (put-be counter 4)))
          for count = (min (length block) (- length position))
          do (replace output block :start1 position :end2 count)
             (incf position count)
             (incf counter))
    output))

(defun rsa-verify-pss (algorithm modulus exponent message signature
                       &key (salt-length (digest-length algorithm)))
  "Verify an RSASSA-PSS signature for MESSAGE."
  (%rsa-validate-public-key modulus exponent)
  (unless (member algorithm '(:sha1 :sha256 :sha384 :sha512))
    (crypto-error "Unsupported RSA-PSS digest algorithm ~S" algorithm))
  (unless (and (integerp salt-length) (>= salt-length 0))
    (crypto-error "Invalid RSA-PSS salt length"))
  (let* ((modulus-bits (integer-length modulus))
         (signature-size (ceiling modulus-bits 8))
         (em-bits (1- modulus-bits))
         (em-size (ceiling em-bits 8))
         (h-length (digest-length algorithm))
         (db-length (- em-size h-length 1))
         (em (%rsa-recover-em signature modulus exponent)))
    (when (or (null em) (< em-size (+ h-length salt-length 2)))
      (return-from rsa-verify-pss nil))
    (when (= signature-size (1+ em-size))
      (unless (zerop (aref em 0))
        (return-from rsa-verify-pss nil))
      (setf em (subseq em 1)))
    (let* ((masked-db (subseq em 0 db-length))
           (hash (subseq em db-length (+ db-length h-length)))
           (trailer (aref em (1- em-size)))
           (unused-bits (- (* 8 em-size) em-bits)))
      (unless (and (= trailer #xbc)
                   (or (zerop unused-bits)
                       (zerop (ldb (byte unused-bits (- 8 unused-bits))
                                   (aref masked-db 0)))))
        (return-from rsa-verify-pss nil))
      (let ((db (copy-seq masked-db)))
        (let ((mask (%rsa-mgf1 algorithm hash db-length)))
          (loop for i below db-length
                do (setf (aref db i) (logxor (aref masked-db i)
                                             (aref mask i)))))
        (when (> unused-bits 0)
          (setf (aref db 0) (logand (aref db 0) (1- (ash 1 (- 8 unused-bits))))))
        (let ((padding-length (- db-length salt-length 1)))
          (unless (and (>= padding-length 0)
                       (loop for i below padding-length always (zerop (aref db i)))
                       (= (aref db padding-length) 1))
            (return-from rsa-verify-pss nil))
          (let* ((salt (subseq db (1+ padding-length)))
                 (expected (digest algorithm
                                   (concat-octets (make-array 8 :element-type '(unsigned-byte 8)
                                                               :initial-element 0)
                                                  (digest algorithm message) salt))))
            (constant-time-equal hash expected)))))))

(defun verify-rsa-pss (&rest arguments)
  (apply #'rsa-verify-pss arguments))
